import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Componentes
import { SideBar } from "@/components/SideBar";
import { Navbar } from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "App flights",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex w-full h-full">
              <div className="hidden xl:block w-80 h-full xl:fixed">
                  <SideBar />
              </div>
              <div className="w-full xl:ml-80">
                  <Navbar />
                  <div className="p-6 bg-[#cecfcf] dark:bg-secondary">
                      {children}
                  </div>
              </div>
          </div>
      </body>
    </html>
  );
}
